### ISSUE TITLE
Page on mobile view not work properly

### ISSUE THREAD

**Issue by Vsynyster1** [Aircoin-official/AirCash#101]
There some bug i think. When i try open on mobile mode, page not open properly. When i try to connect wallet, it is not connect. There some evidence about page not open properly : 
![Screenshot_20211217-214522_Samsung Internet](https://user-images.githubusercontent.com/96302016/146562642-4dc1eb01-723f-4be0-91d9-7e51984de2b2.jpg)

**Comment by Satoshiisgod** [comment]
Thanks, AirCash mobile version is on the way.
