### ISSUE TITLE
Screen OPTIMIZATION

### ISSUE THREAD

**Issue by Biggestheart** [Aircoin-official/AirCash#103]
Screen OPTIMIZATION should be fit to screen then there should be this place where you can change it to either desktop view...

**Comment by Arrhnnie** [comment]
The reason is this so you won't have to be dragging your screen around ...

Newbies might find this difficult.

**Comment by Biggestheart** [comment]
The reason is this so that users won't have to be dragging your screen around.

Especially newbie might have difficulty at this stage.
Please consider this

**Comment by Biggestheart** [comment]
![Screenshot_20211217-172227](https://user-images.githubusercontent.com/57988686/146577233-3efed0b4-e2ee-474f-980a-3fc63715bc6c.png)

This is a clear example.

**Comment by Biggestheart** [comment]
When you click connect you'll have to be search around from here

**Comment by Satoshiisgod** [comment]
Thanks, the AirCash mobile version is on the way.
