### ISSUE TITLE
The messenger window sometimes doesn’t work.

### ISSUE THREAD

**Issue by hjwanthony** [Aircoin-official/AirCash#104]
![1D24966A-EF55-41D3-A07C-75EF3F0AF533](https://user-images.githubusercontent.com/85868617/146576747-31d2ed75-80dc-4bdd-8a33-26f921b2e78a.jpeg)

**Comment by Satoshiisgod** [comment]
Thanks and noted, it is a peer-to-peer messager, so you need to connect to peers before messaging.
