### ISSUE TITLE
Issues connecting with phone

### ISSUE THREAD

**Issue by IAmWhisperingshadow** [Aircoin-official/AirCash#107]
I'm testing the AirCash site with my phone, the site does not optimize well with mobile phone and you should understand that most traders trades with their phone. Also the site is very slow and do not load quickly. Please do some thing about that, when I tried connecting it with my wallet, it brings error, I have to try it consistently before it connects. After connecting it takes forever to bring up anything after pressing trade. All it brings out is blank space nothing more. Try to make it more accessible for mobile phones and more easy for newbies. Thanks
#UPDATE
It later display, I tried locking the aircoin test net token, it never stop loading, I decide to attach a screenshot picture taken
![Screenshot_20211217-234050](https://user-images.githubusercontent.com/81260002/146616297-ffa559fc-4c18-449f-89d6-8a24ea7c981a.png)

Anytime I change offline to online, it goes back  offline

**Comment by Satoshiisgod** [comment]
Thanks, you need to switch to BSC Testnet before testing.
