### ISSUE TITLE
BUG：unlock

### ISSUE THREAD

**Issue by ticketid** [Aircoin-official/AirCash#112]
No longer is the merchant when I unlock.
But I still have more than 10,000,000,000.

**Comment by Rezka2003** [comment]
Send my coin hhe


Pada tanggal Min, 19 Des 2021 10.39, ticket id ***@***.***>
menulis:

**Comment by Satoshiisgod** [comment]
Thanks, we have fixed this issue.

**Comment by Kaung5321** [comment]
Good project
