### ISSUE TITLE
Merchant privacy

### ISSUE THREAD

**Issue by Adoesom** [Aircoin-official/AirCash#118]
I'll say in countries where crypto is banned, the developers should generate a customised message to include random description that's on a safer side alongside Account details of the merchant.

For example if I'm the buyer, where I will see account details of a merchant should be something like this

Send (amount) to
Account number of merchant/username (in the case of raven)
Description (use only this description): (For Trading/For our discussion/For ongoing transaction etc)

In addition, if only raven account can be use in Nigeria, then only username will be enough and protection can be guaranteed.

However, with caution other banks can also be used

One of this description can be shown to a buyer and instructed to use only

**Comment by Princedollar** [comment]
I'm from Nigeria, how to get raven account?

**Comment by Kaikam92** [comment]
Through Trust Wallet

**Comment by Satoshiisgod** [comment]
Thanks, bro, noted, we will improve the ue.
