### ISSUE TITLE
Nice!

### ISSUE THREAD

**Issue by cryptoonur0** [Aircoin-official/AirCash#20]
To The Moon!

**Comment by Ks298561** [comment]
Nyc project

**Comment by 1996999111** [comment]
Go go go,, succes

**Comment by firozkaziK** [comment]
Nice

**Comment by adamparol** [comment]
Let's get it done, everyone 😀

**Comment by cryptoonur0** [comment]
Hello, friends, :D I'm a stranger to the Fork system. I can't do the Fork process. Do you have that might help? I get mistakes all the time. I'm supposed to be a member, but I don't know what to be a member of.
