### ISSUE TITLE
I hope success project

### ISSUE THREAD

**Issue by petrpam28** [Aircoin-official/AirCash#25]
Air Coin fot the future life

**Comment by Indra051091** [comment]
Semoga sukses

**Comment by Indra051091** [comment]
Great project

Pada tanggal Sel, 20 Jul 2021 04.53, petrpam28 ***@***.***>
menulis:

**Comment by Gilludsz** [comment]
0x582f78281558c3487b6F2F639E7C5CcE1a4EbF1C

**Comment by Gilludsz** [comment]
Your project is promising. Great efforts by team

**Comment by ppppppk** [comment]
Nice

**Comment by ppppppk** [comment]
Nice project

**Comment by Indra051091** [comment]
Thank you!

Pada tanggal Sel, 20 Jul 2021 09.36, ppppppk ***@***.***>
menulis:
