### ISSUE TITLE
AirCash

### ISSUE THREAD

**Issue by Henrae01** [Aircoin-official/AirCash#32]
It is on developing.

AirCash system will be online within 3 months.

**Comment by VitAnh2412** [comment]
I received a notification email from you and I reply

**Comment by Vobner** [comment]
Hey, what is this project all about. Can we get some guidelines to start coding

**Comment by bleagle5** [comment]
The AIR project started from a meme coin.
It was issued to mock the madness of the cryptocurrency market.
$ * The first product is called AirPool, a pool system for DeFi mining.
$** The second product is called AirSwap, a decentralized exchange system.
$***" The third  product is called AirCash, a cash system for AIR.
Although AIR is only a BSC token now, it will be one of the biggest ecosystems in the crypto world.

    On Wednesday, July 21, 2021, 04:30:42 PM GMT+3, Stonks3232 ***@***.***> wrote:  
 
 


Hey, what is this project all about. Can we get some guidelines to start coding
