### ISSUE TITLE
Aircoin

### ISSUE THREAD

**Issue by web3sahb** [Aircoin-official/AirCash#38]
Lets fet the Air

**Comment by azmi0** [comment]
very good Project

**Comment by Thonny579gamer** [comment]
excellent project

**Comment by NguyenJ20** [comment]
Nice project

**Comment by tersyolnyolcusu** [comment]
ıf community can driven well this project too can grow more better

**Comment by hahahalsq** [comment]
very good project

**Comment by Ibagbea** [comment]
Good project

**Comment by Riyajctg0** [comment]
This project is very strong. 
I proud this project.

**Comment by Simon0694** [comment]
It will moon soon

**Comment by Satoshiisgod** [comment]
Dear AirCoiner,

Thanks for your Trust.

Our D&R team has received your application, and we will review your application as soon as possible.

Thanks again, and we wish you a great day.

Best Regards,

Yolo Sana
