### ISSUE TITLE
Why this repository has 2.5k stars while has almost no source code at all?

### ISSUE THREAD

**Issue by fatihky** [Aircoin-official/AirCash#39]

**Comment by ccinv** [comment]
they starred for airdrop

**Comment by weisk** [comment]
because they decided to start from scratch, using rust

so they `git log --oneline | tail -n 1 | awk '{print $1}' | xargs git reset --hard`

and then they `git push --force`

**Comment by fauzizz** [comment]
I'm agree with weisk
