### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by herrie23** [Aircoin-official/AirCash#4]
Go to moon

**Comment by Chimnecherem** [comment]
Mail received but not understood

**Comment by herrie23** [comment]
Thank's

Pada tanggal Sen, 12 Jul 2021 18:08, Chimnecherem ***@***.***>
menulis:

> Mail received but not understood
>

**Comment by Jummie6** [comment]
Thanks

**Comment by theinmyinttun009** [comment]
Good Project

**Comment by theinmyinttun009** [comment]
Good
