### ISSUE TITLE
apply for volunteers

### ISSUE THREAD

**Issue by underthewater** [Aircoin-official/AirCash#41]
apply for AirCash volunteers

**Comment by Sunildutt1990** [comment]
Send me my token

**Comment by zlcolin2025** [comment]
apply for AirCash volunteers too.

**Comment by underthewater** [comment]
0xd8a2ae43fd061d24acd538e3866ffc2c05151b53

Sunildutt1990 ***@***.***> 于2021年9月14日周二 下午2:53写道：

**Comment by Ganadineroseguro1** [comment]
You are wrong I will report your email address if you keep sending spam

**Comment by YuChen829** [comment]
Dear friends of Aircoin
I'm Yuchen（Chinese name：誉程）A member of the air billionaire community.
I’d like to be the volunteer of the Aircash software internal test. I sure understand some blockchain knowledge and have a certain foundation in English. I have made up my mind and can't wait to test the new software with my colleagues.

**Comment by imronsiu** [comment]
Dear friends of Aircoin
I'm RONSIU A member of the air billionaire community.
I’d like to be the volunteer of the Aircash software internal test. I sure understand some blockchain knowledge and have a certain foundation in English. I have made up my mind and can't wait to test the new software with my colleagues.

**Comment by Satoshiisgod** [comment]
> apply for AirCash volunteers too.

Thanks, please open a new issue.

**Comment by Satoshiisgod** [comment]
> Dear friends of Aircoin
> I'm Yuchen（Chinese name：誉程）A member of the air billionaire community.
> I’d like to be the volunteer of the Aircash software internal test. I sure understand some blockchain knowledge and have a certain foundation in English. I have made up my mind and can't wait to test the new software with my colleagues.

Thanks, please open a new issue.

**Comment by Satoshiisgod** [comment]
> apply for AirCash volunteers too.

Thanks, please open a new issue.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
