### ISSUE TITLE
apply for volunteers

### ISSUE THREAD

**Issue by hao-web** [Aircoin-official/AirCash#43]
it's my pleasure.

**Comment by hao-web** [comment]
Hello, I want to sign up as a volunteer for the AIRcash software test. I understand some blockchain knowledge and have a certain foundation in English.
> I very much look forward to volunteers who can participate in this test.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
