### ISSUE TITLE
 Apply for volunteers of AIRCASH

### ISSUE THREAD

**Issue by Maggiemuscle** [Aircoin-official/AirCash#44]
Dear friends of Aircoin：

I'm Maggie MA(Chinsese name:XIUXIU MA)，A member of the AIR Chinese Community.
I’d like to be a volunteer of the Aircash software internal test.
I sure understand some blockchain knowledge and have a certain foundation in English.
Besides, I‘m good at Data Analysing.
I have made up my mind and can't wait to test the new software with my colleagues.

Hope for your reply!

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
