### ISSUE TITLE
Apply for volunteer of aircoin test

### ISSUE THREAD

**Issue by YuChen829** [Aircoin-official/AirCash#45]
Dear friends of Aircoin
I'm Yuchen（Chinese name：誉程）A member of the air billionaire community.
I’d like to be the volunteer of the Aircash software internal test. I sure understand some blockchain knowledge and have a certain foundation in English. I have made up my mind and can't wait to test the new software with my colleagues.
Looking forward to get your reply to my sign up.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
