### ISSUE TITLE
Dear friends of Aircoin I Want To Apply for volunteer of aircoin test

### ISSUE THREAD

**Issue by imronsiu** [Aircoin-official/AirCash#46]
I'm RONSIU A member of the air billionaire community. I’d like to be the volunteer of the Aircash software internal test. I sure understand some blockchain knowledge and have a certain foundation in English. I have made up my mind and can't wait to test the new software with my colleagues.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
