### ISSUE TITLE
Apply for volunteer of AIR CASH test.  

### ISSUE THREAD

**Issue by linhuiyin111** [Aircoin-official/AirCash#47]
Hello, I want to sign up as a volunteer for the AIRcash software test. I understand some blockchain knowledge and have a certain foundation in English.
I very much look forward to volunteers who can participate in this test.

**Comment by Burningart** [comment]
Hello I love to be part of this amazing testnet project already tested more 100 projects experience in past love to work as a volunteer of air cash thanks wish you alot of success thanks God bless you

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
