### ISSUE TITLE
Application for participating in test of OTC

### ISSUE THREAD

**Issue by hjwanthony** [Aircoin-official/AirCash#49]
Hello there,
I want to join the volunteers to test the OTC Aircash.  I majored in English and have some basic knowledge in block chain.  Hope I am qualified and look forward to hearing from you soon.

Best regards,

Anthony Hu

**Comment by alswede0101** [comment]
0x423d71371CFaE9301998fFE52b3A9C6398b3D724
‫أُرسلت من الـ iPhone‬

**Comment by hjwanthony** [comment]
Hello,
Have you finished the Aircash testing volunteers recruiting?  It seems that I have n’t got the opportunity, doesn’t it?  I sincerely hope that I can be one of them.  I am good at English and I am working as an IT supporting engineer in my company.  I think I am qualified for the task.  Please re-consider for my application.
Best regards,
Anthony Hu

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
