### ISSUE TITLE
Greatly

### ISSUE THREAD

**Issue by perfectsuccess** [Aircoin-official/AirCash#5]
Great project

**Comment by Iykedivine** [comment]
Awesome

**Comment by indoairdrop7** [comment]
***@***.***

Pada tanggal Sab, 17 Jul 2021 01.45, perfectsuccess <
***@***.***> menulis:

**Comment by Oyebola2508** [comment]
Nice

**Comment by indoairdrop7** [comment]
Yes please

0x654c20D5FAf50b87d787Df330339Bf59e51E46f8

 Joining the airdrop

Pada tanggal Sab, 17 Jul 2021 02.34, Oyebola2508 ***@***.***>
menulis:

**Comment by ndaesbero** [comment]
0xA82eE1c73eFa4BD73460E20989B0cB4eb85e3CEe

Pada tanggal Sab, 17 Jul 2021 01.45, perfectsuccess <
***@***.***> menulis:

**Comment by urinvitein** [comment]
Nice project

**Comment by Munnanycle** [comment]
Very interesting project I hope growing up the project and fly the sky

**Comment by indoairdrop7** [comment]
Thank you for your support!


Pada tanggal Sab, 17 Jul 2021 13.43, Munnanycle ***@***.***>
menulis:

**Comment by Oyebola2508** [comment]
0x15f3e1C0677369f3138E0683eC90b5B65137b5f4

**Comment by indoairdrop7** [comment]
0x15f3e1C0677369f3138E0683eC90b5B65137b5f4

Not my adress


This my adress from airdrop

0x654c20D5FAf50b87d787Df330339Bf59e51E46f8



Pada tanggal Sab, 17 Jul 2021 22.47, Oyebola2508 ***@***.***>
menulis:

**Comment by Oyebola2508** [comment]
What do I do with the address thought y'all posting address

**Comment by indoairdrop7** [comment]
Im not received the airdrop air

0x654c20D5FAf50b87d787Df330339Bf59e51E46f8

this my adress on airdrop google form

Pada tanggal Sab, 17 Jul 2021 23.07, Oyebola2508 ***@***.***>
menulis:

**Comment by Oyebola2508** [comment]
Oh ok

**Comment by indoairdrop7** [comment]
Thank you!

Pada tanggal Sab, 17 Jul 2021 23.20, Oyebola2508 ***@***.***>
menulis:

**Comment by Oyebola2508** [comment]
Yh , but is distribution on

**Comment by indoairdrop7** [comment]
I'm waiting for the airdrop to arrive in my swallow, thank you

Pada tanggal Sab, 17 Jul 2021 23.43, Oyebola2508 ***@***.***>
menulis:
