### ISSUE TITLE
Apply for volunteer of AIR CASH test

### ISSUE THREAD

**Issue by xingkong2993** [Aircoin-official/AirCash#52]
Dear technical team members, Hello, I am an Followers and believers of air coins also hold a certain number of air coins in their hands. I am willing to sign up for the test, I have a certain base for the use of blockchain and wallet.thank you.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
