### ISSUE TITLE
Air otc test application

### ISSUE THREAD

**Issue by tian1105002358** [Aircoin-official/AirCash#54]
Hello,  air's development team. I'm TianQi, I'm willing to do my part for the ecological application of air, I hope I can get this otc test opportunity.
looking forward to your reply！
Thanks～

**Comment by Emmatex19952020** [comment]
Your application has been accepted but you have to pass this text which
will also reward you at the end ,click and register on the below link ,pass
the verification process, request for 3000# loan ,pay back the 3000# when
the loan is granted. I don't have to tell you to avoid greed else you will
fail the test
Good luck!!!!

Your friend invites you to use LCredit. Register now to receive N200 cash
voucher immediately. If you successfully borrow money, you can withdraw
N1500 cash reward immediately.
https://lcredit.ng/#/invite_new?userGid=23239492-fa25-40e7-9bf4-cabe552d3fa9&activityId=4

**Comment by kunmih** [comment]
Emmatex19952020 mail is a scam. Do not fall for it.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
