### ISSUE TITLE
Great

### ISSUE THREAD

**Issue by Tbparseval** [Aircoin-official/AirCash#6]
Beautiful project. Good Sensations

**Comment by indoairdrop7** [comment]
Yes

Pada tanggal Min, 18 Jul 2021 04.29, Tbparseval ***@***.***>
menulis:

**Comment by hsueaintsan** [comment]
🔥🔥🔥

**Comment by tjetjun** [comment]
what is fork and clone ?

**Comment by Atalispro** [comment]
Good

**Comment by Dul19** [comment]
good project i love this air

**Comment by Rexnali78** [comment]
Great project
