### ISSUE TITLE
AirCash测试志愿者报名

### ISSUE THREAD

**Issue by leebeeboooo** [Aircoin-official/AirCash#68]
你好，我想以志愿者的身份参加AirCash产品测试。
本人有一定的英文基础，并熟练使用谷歌等翻译软件；对区块链基础知识有一定了解；学习能力较强，喜欢接触新鲜事物；居家办公自由工作时间。
期待能够参与到这次产品测试，并能出自己一份微薄的力量。
谢谢！

**Comment by AAJOB** [comment]
Yes
