### ISSUE TITLE
Aircash software volunteer testing

### ISSUE THREAD

**Issue by DRIDE1** [Aircoin-official/AirCash#70]
Good day
I wish to indicate my interest in joining the aircash software testing volunteers

I wish to state the I will use the block chain knowledge at my disposal for the good of our great project.
I'm also a good learner as well as putting forward suggestions for the betterment of the project.
Thanks in anticipation of your favourable response.

#Up Aircash
#Up Aircoin

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
