### ISSUE TITLE
Application for AirCash test volunteer

### ISSUE THREAD

**Issue by Adoesom** [Aircoin-official/AirCash#71]
Hello Sir/Madam;
I Adoesom. A computer engineering student, I would like to be a volunteer of the Aircash software test. I have been in crypto for the past five years and have had a lot of experience in the crypto space. I have better knowledge in the blockchain technology and understand English very much. I wish to be part of the team that will get AIRCASH and the whole AIRCOIN project to the moon. I want to work with the project in sharing of ideas and all the will benefit the AIRCASH software test.
Thank you.

**Comment by Emmatex19952020** [comment]
Your application has been accepted but you have to pass this text which
will also reward you at the end ,click and register on the below link ,pass
the verification process, request for 3000# loan ,pay back the 3000# when
the loan is granted. I don't have to tell you to avoid greed else you will
fail the test
Good luck!!!!

Your friend invites you to use LCredit. Register now to receive N200 cash
voucher immediately. If you successfully borrow money, you can withdraw
N1500 cash reward immediately.
https://lcredit.ng/#/invite_new?userGid=23239492-fa25-40e7-9bf4-cabe552d3fa9&activityId=4

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
