### ISSUE TITLE
Letter of application for Voluntary testing of AirCash component

### ISSUE THREAD

**Issue by Oly4gr8** [Aircoin-official/AirCash#72]
Hello, Aircoinreal team i hope this message finds you well, I'm Toluwase, A Nigerian student that has vast knowledge on crypto currency and blockchain generally. 
In response to your quest for able-bodied and knowledgeable people in other to put your project into test.. Well I have read all the requirements, and I meet the demands plus I hold a diploma in Electrical Electronics Engineering technology and have done series of courses in Crypto and Blockchain generally. 
I hereby make my request to among the volunteers, known to the team.

I hope to hear from you soon with a good and positive response. 

Regards 

Toluwase.

**Comment by Emmatex19952020** [comment]
Your application has been accepted but you have to pass this text which
will also reward you at the end ,click and register on the below link ,pass
the verification process, request for 3000# loan ,pay back the 3000# when
the loan is granted. I don't have to tell you to avoid greed else you will
fail the test
Good luck!!!!

Your friend invites you to use LCredit. Register now to receive N200 cash
voucher immediately. If you successfully borrow money, you can withdraw
N1500 cash reward immediately.
https://lcredit.ng/#/invite_new?userGid=23239492-fa25-40e7-9bf4-cabe552d3fa9&activityId=4

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
