### ISSUE TITLE
Apply for Air cash test

### ISSUE THREAD

**Issue by GH3336699** [Aircoin-official/AirCash#73]
Hello, I want to apply for the air coin test.
I used to be the general manager of IT projects. I started to understand the blockchain in 2016 and later became a merchant of other exchanges. I still understand this aspect quite well.
I am very interested in Air Cash, and I hereby apply, hoping to become a member of Air Cash and contribute to Air Cash.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
