### ISSUE TITLE
Application for Aircash volunteer Test

### ISSUE THREAD

**Issue by Succes4mula** [Aircoin-official/AirCash#74]
Hello 
I'm Jeremiah by name, I'm a Nigeria student 
 who knows much on crypto currency and block chain system in general
In response to the the requirements I can speak a very fluent English and I have been on the crypto currency space for the past 5years which this as certified me with a lot of experience 
I have a fast learning ability that's what has made me the best in learning aspects 
I'm here by wishing to work with the entire Air Team 
I hope to hear from you very soon with a nice response on the application
Thanks.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
