### ISSUE TITLE
AirCash测试志愿者申请

### ISSUE THREAD

**Issue by cz398562295011** [Aircoin-official/AirCash#75]
1.有一定的英语基础，较强的学习能力。
2.对区块链的基础比较了解，能清晰清楚OTC流程
3.学习能力较强。
我想我可以为AirCash的功能的测试提供自己的帮助。

**Comment by joey2020-hulk** [comment]
I want to be part of the air cash volunteer test

**Comment by cz398562295011** [comment]
OK


joey2020-hulk ***@***.***> 于2021年9月15日周三 下午2:16写道：
