### ISSUE TITLE
Apply for Aircash volunteers

### ISSUE THREAD

**Issue by selinalau** [Aircoin-official/AirCash#79]
Dear Sir,
I am Selina Lau A member of the air thousand billionaire community . I would like to be the volunteer of the Aircash software internal text, I understand some blockchain knowledge, I have a certain foundation in English, I am so much interesting and looking forward to be volunteers.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
