### ISSUE TITLE
AIR test volunteer application

### ISSUE THREAD

**Issue by rointixo** [Aircoin-official/AirCash#80]
Dear AIR Coin team：
Hello, I want to sign up as a volunteer for the AIRcash software test. I understand some blockchain knowledge and have a certain foundation in English.
I am an old AIR trillion holder, and I have now migrated to the new AIR.  I very much look forward to volunteers who can participate in this test.

**Comment by rointixo** [comment]
Dear AIR Coin team：
Hello, I want to sign up as a volunteer for the AIRcash software test. I understand some blockchain knowledge and have a certain foundation in English.
I am an old AIR trillion holder, and I have now migrated to the new AIR. I very much look forward to volunteers who can participate in this test.

**Comment by rointixo** [comment]
Dear AIR Coin team：
Hello, I want to sign up as a volunteer for the AIRcash software test. I understand some blockchain knowledge and have a certain foundation in English.
I am an old AIR trillion holder, and I have now migrated to the new AIR. I very much look forward to volunteers who can participate in this test.

**Comment by rointixo** [comment]
Dear AIR Coin team：
Hello, I want to sign up as a volunteer for the AIRcash software test. I understand some blockchain knowledge and have a certain foundation in English.
I am an old AIR trillion holder, and I have now migrated to the new AIR. I very much look forward to volunteers who can participate in this test.

**Comment by Sulivanmk** [comment]
BSC 0x33594D428931305c62C699262ef3954b31625F21
-------- Mensagem original --------De : rointixo ***@***.***> Data: 17/09/2021  10:40  (GMT-03:00) Para: Aircoin-official/AirCash ***@***.***> Cc: Subscribed ***@***.***> Assunto: Re: [Aircoin-official/AirCash] AIR test volunteer application (#80) 

Dear AIR Coin team：

Hello, I want to sign up as a volunteer for the AIRcash software test. I understand some blockchain knowledge and have a certain foundation in English.

I am an old AIR trillion holder, and I have now migrated to the new AIR. I very much look forward to volunteers who can participate in this test.

**Comment by Satoshiisgod** [comment]
OK, you are really outstanding and helpful.

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
