### ISSUE TITLE
apply for volunteer tester 

### ISSUE THREAD

**Issue by bianyuanop** [Aircoin-official/AirCash#81]
Major in Computer Science. 
Have implemented a contract of ICP(internet computer)
Good knowledge of project reading and debugging.
Substrate blockchain user. Knowing about the related  contract language ink!
Familiar with c/cpp/rust/go/js language 

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
