### ISSUE TITLE
 Apply for volunteer of AIR CASH test

### ISSUE THREAD

**Issue by K1LiG** [Aircoin-official/AirCash#84]
Hello, I would like to participate in the AirCash product test as a volunteer.                                                                                                 
    I have a good command of English and am proficient in Google translation software. Basic knowledge of blockchain; Strong learning ability, like to contact new things; Home office free working hours. I am looking forward to participating in this product test and contributing my meager strength. Thank you very much!

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
