### ISSUE TITLE
APPLICATION FOR VOLUNTEER OF AIRCASH TEST.

### ISSUE THREAD

**Issue by JohnnyTimm** [Aircoin-official/AirCash#87]
I am a crypto and blockchain enthusiast, who is eager to offering durable improvement to the LocalCoinSwap Project through my unrelenting endeavour with 2years plus in working and moderating of community projects.

 My specialized understanding of cryptocurrency and my interpersonal skill accompany with awareness to details warranties that I'm knowledgeable in conveying the best quality information needed.

So as a result of that, I will like to be one the Ambassador and a volunteer of aircash test.
I will be looking forward to hearing from you.

**Comment by Satoshiisgod** [comment]
OK, you are really outstanding and helpful.

**Comment by JohnnyTimm** [comment]
Thanks
Looking forward to hear from you

**Comment by Satoshiisgod** [comment]
Anyone who applied for the AirCash testing please join the discord channel for test volunteers.
https://discord.gg/eRSY7NtxZA
