### ISSUE TITLE
Diverse write up of Air guideline in different languages

### ISSUE THREAD

**Issue by zearealistic** [Aircoin-official/AirCash#94]
Hello my Name is Justice

Just discovered an issue in Air coin and needs attention,

This issue is how to get a write up of Air guideline in other languages and designing banners for air promotion

How to solve part of this issue,
If I can get the Air guideline I will translate in my  language igbo and if given permission I will give some beautiful banner designs of Air coin in english or in igbo

My whatsapp line is 08067856131
My Telegram username is @cryptozeareal2

Anticipating your response

Thanks

**Comment by samuel482** [comment]
Yes ello

**Comment by Satoshiisgod** [comment]
Please join the DIscord channel.

https://discord.gg/DHKmBRzp

**Comment by yantoaja** [comment]
0x1fae34b40E142C372105e417f541DeCD5Bc344B9
