### ISSUE TITLE
Promotion materials 

### ISSUE THREAD

**Issue by Ezewa** [Aircoin-official/AirCash#95]
Hello air team 

Thumbs up so far and so good for the good work you are doing.

I want to point out some important suggestion on the promotion if Air coin.

1. I will love the Air team to produce materials like T. Shirts, face cap, hand bands etc.. and share to their promoters especially the serious ones to were around as they promote air coin. This will make people to ask questions and get interested.
2. The team should come up with a competitions and programs that will engage subscribers and investors 
3. The team should encourage promoters to produce materials like videos, pictures, banner, stickers etc... Using their native language 
4. I want the team to consider me and give me the igbo translation in the discord group as I have already started working on it. I need your encouragement to continue

Thanks Air to the moon🚀🚀

**Comment by Satoshiisgod** [comment]
Thanks.
